language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.8.7
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode 
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    rvm:
      - 1.9.2        # Disabled for problems with rake
      - jruby-18mode # Disabled for core dump on travis http://travis-ci.org/#!/mbj/veritas-elasticsearch-adapter/jobs/1769741
      - jruby-19mode # Disabled for core dump on travis http://travis-ci.org/#!/mbj/veritas-elasticsearch-adapter/jobs/1768119
notifications:
  email:
    - mbj@seonic.net
