language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.8.7
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode 
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: 1.9.2         # Disabled for problems with ruby-parser https://travis-ci.org/mbj/auom/jobs/3565192
    - rvm: jruby-19mode  # Disabled for inconistend metric reports
notifications:
  email:
    - mbj@seonic.net
